spring.application.name=mallapi

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/malldb
spring.datasource.username=malldbuser
spring.datasource.password=malldbuser

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true


!과도한 비용 방지
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=5

!파일 업로드와 썸네일처리(섹션5)
spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.max-file-size=10MB
org.yujin.upload.path=upload

!security 로그찍기
logging.level.org.springframework.security.web=trace