spring.application.name=mallapi

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

!과도한 비용 방지
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=5

!파일 업로드와 썸네일 처리
spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.max-file-size=10MB

!security 로그찍기
logging.level.org.springframework.security.web=trace

!S3 연동
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region.static=${AWS_REGION}
cloud.aws.s3.bucket=${AWS_S3_BUCKET}